name: macos

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  brew:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11, macos-12]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@main

      - run: |
          cmake \
            -S . \
            -B build.d \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
            -DANDROID_TOOLCHAIN=clang \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=21 \
            -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=OFF
