name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  vcpkg:

    env:
      DEBIAN_FRONTEND: noninteractive
      TZ: Asia/Shanghai

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [20.04, 22.04]

    container: ubuntu:${{ matrix.version }}

    steps:
      - uses: actions/checkout@main

      - run: |
          cmake \
            -S . \
            -B build.d \
            -DCMAKE_VERBOSE_MAKEFILE=ON \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
            -DANDROID_TOOLCHAIN=clang \
            -DANDROID_ABI=arm64-v8a \
            -DANDROID_PLATFORM=21 \
            -DANDROID_USE_LEGACY_TOOLCHAIN_FILE=OFF

      - run:  cmake --build   build.d
